version: '2'

services:
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: php7
        volumes:
            - ./symfony/${APP_NAME}:/var/www/html
            - ./logs/symfony:/var/www/html/app/logs
    base:
        image: kretin2/er2-base
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
      ports:
        - 8080:80